@startuml
!include C4_Dynamic.puml

AddElementTag($tagStereo="backup", $fontColor="orange")
AddElementTag($tagStereo="v1.0", $borderColor="#d73027")
AddElementTag($tagStereo="v1.1", $fontColor="#d73027")

AddRelTag($tagStereo="backup", $textColor="orange", $lineColor="orange", $lineStyle="DashedLine()")

Person($alias=17, $label="Customer", $descr="People that need products")
Person($alias=18, $label="Administrator", $descr="People that administrates the products via the new v1.1 components", $tags="v1.1")

Container($alias=19, $label="SPA", $descr="The main interface that the customer interacts with via v1.0", $techn="angular", $tags="v1.0")
Container($alias=20, $label="Admin SPA", $descr="The administrator interface that the customer interacts with via new v1.1", $techn="angular", $tags="v1.1")
Container($alias=21, $label="API", $descr="Handles all business logic (incl. new v1.1 extensions)", $techn="java", $tags="v1.0+v1.1")
ContainerDb($alias=22, $label="Database", $descr="Holds product, order and invoice information", $techn="Microsoft SQL")
Container($alias=23, $label="Archive", $descr="Stores 5 years", $techn="Audit logging", $tags="backup")

Rel($from=17, $to=19, $label="Uses", $techn="https")
Rel($from=19, $to=21, $label="Uses", $techn="https")
Rel_Right($from=21, $to=22, $label="Reads/Writes")
Rel($from=18, $to=20, $label="Uses", $techn="https")
Rel($from=20, $to=21, $label="Uses", $techn="https")
Rel_Left($from=21, $to=23, $label="Writes", $techn="messages")

SHOW_LEGEND()
@enduml
