@startuml
!include C4_Dynamic.puml
Person($alias=139974568411088, $label="Label", $descr="Optional Description")
System($alias=139974568408848, $label="Label", $descr="Optional Description")
Container($alias=139974568395024, $label="Label", $descr="Optional Description", $techn="Technology")
Rel($from=139974568411088, $to=139974568395024, $label="Label", $techn="Optional Technology")
@enduml
