@startuml
!include C4_Dynamic.puml
Person($alias=139896624833744, $label="Label", $descr="Optional Description")
System($alias=139896624889296, $label="Label", $descr="Optional Description")
Container($alias=139896624877200, $label="Label", $descr="Optional Description", $techn="Technology")
Rel($from=139896624833744, $to=139896624877200, $label="Label", $techn="Optional Technology")
@enduml
