@startuml
!include C4_Dynamic.puml
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/user>

Person($alias=9, $label="Administrator", $sprite=user, $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#hide_person_sprite-or-show_person_spritesprite")
System_Boundary($alias=11, $label="Sample System", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
    Container($alias=10, $label="Web Application", $descr="Allows users to compare multiple Twitter timelines", $techn="C#, ASP.NET Core 2.1 MVC", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/masterLayoutOptions.md")
}
System($alias=12, $label="Twitter", $link="https://github.com/plantuml-stdlib/C4-PlantUML")

Rel($from=9, $to=10, $label="Uses", $techn="HTTPS", $link="https://plantuml.com/link")
Rel($from=10, $to=12, $label="Gets tweets from", $techn="HTTPS", $link="https://plantuml.com/link")
@enduml
