@startuml
!include C4_Dynamic.puml
Person($alias=139896631567760, $label="Customer", $descr="People that need products")
Container($alias=139896624968080, $label="SPA", $descr="The main interface that the customer interacts with", $techn="angular")
Container($alias=139896624955856, $label="API", $descr="Handles all business logic", $techn="java")
ContainerDb($alias=139896631558992, $label="Database", $descr="Holds product, order and invoice information", $techn="Microsoft SQL")
Rel($from=139896631567760, $to=139896624968080, $label="Uses", $techn="https")
Rel($from=139896624968080, $to=139896624955856, $label="Uses", $techn="https")
Rel_Right($from=139896624955856, $to=139896631558992, $label="Reads/Writes")
@enduml
