%%{init: {'theme':'neutral'}}%%
erDiagram
    pack ||--o{ unit : pack_id
    pallet ||--o{ unit : pallet_id
    pallet ||--o{ pack : pallet_id
    batch ||--o{ unit : batch_id
    batch ||--o{ pack : batch_id
    state ||--o| pack : pack_id
    state ||--o| pallet : pallet_id
    state ||--o| batch : batch_id

    state {
        int state_id PK 
        int pack_id FK 
        int pallete_id FK 
        int batch_id FK "Запущенная партия"
        int max_unit_in_pack  
        int max_pack_in_pallet  
        int max_pallet_in_batch  
    }

    pack {
        int pack_id PK 
        int pallet_id FK 
        int batch_id FK 
        str barcode  "Код без скобок, для печати кода на принтере"
        str barcode_human  "Код со скобками"
        int mass  
        int seat_number  
        datetime timestamp  
        bool need_validate  "Необходимо валидировать сканером"
    }

    pallet {
        int pallet_id PK 
        int batch_id FK 
        str barcode  "Код без скобок, для печати кода на принтере"
        str barcode_human  "Код со скобками"
        int mass  
        int seat_number  
        datetime start_ts  
        datetime end_ts  
        bool need_validate  "Необходимо валидировать сканером"
    }

    batch {
        int batch_id PK 
        int batch_number  
        int bbd_period  "Срок годности в днях"
        str docid  
        bool exported  
        str gtin  
        datetime manufacture_ts  
        datetime start_ts  
        datetime end_ts  
        int unit_mass  
    }

    unit {
        int unit_id PK 
        int pack_id FK 
        int pallet_id FK 
        int batch_id FK 
        str barcode  
        datetime timestamp  
    }


