@startuml

!include C4_Dynamic.puml



Person(140523040554720, $label="Label", $descr="Optional Description")
System(140523040554816, $label="Label", $descr="Optional Description")

Container(140523040554768, $label="Label", $techn="Technology", $descr="Optional Description")


Rel(140523040554720, 140523040554768, "Label", "Optional Technology", "")
SHOW_LEGEND()
@enduml
