@startuml

!include C4_Container.puml



Person(139666997773120, $label="Label", $descr="Optional Description")
System(139666997772688, $label="Label", $descr="Optional Description")

Container(139666997772736, $label="Label", $techn="Technology", $descr="Optional Description")


Rel(139666997773120, 139666997772736, "Label", "Optional Technology", "")
SHOW_LEGEND()
@enduml
