@startuml

!include C4_Container.puml



Person(139642329826112, $label="Label", $descr="Optional Description")
System(139642329825680, $label="Label", $descr="Optional Description")

Container(139642329825728, $label="Label", $techn="Technology", $descr="Optional Description")


Rel(139642329826112, 139642329825728, "Label", "Optional Technology", "")
SHOW_LEGEND()
@enduml
