@startuml

!include C4_Dynamic.puml



Person(140528276273328, $label="Administrator", $descr="")
System_Boundary(140528276273424, $label="Sample System"){
	Container(140528276273376, $label="Web Application", $techn="C#, ASP.NET Core 2.1 MVC", $descr="Allows users to compare multiple Twitter timelines")

}
System(140528276273472, $label="Twitter", $descr="")



Rel(140528276273328, 140528276273376, "Uses", "HTTPS", "")
Rel(140528276273376, 140528276273472, "Gets tweets from", "HTTPS", "")
SHOW_LEGEND()
@enduml
