@startuml

!include C4_Dynamic.puml
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/user>


Person(140523039151184, $label="Administrator", $descr="", $sprite="user", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#hide_person_sprite-or-show_person_spritesprite")
System_Boundary(140523039151280, $label="Sample System", $link="https://github.com/plantuml-stdlib/C4-PlantUML"){
	Container(140523039151232, $label="Web Application", $techn="C#, ASP.NET Core 2.1 MVC", $descr="Allows users to compare multiple Twitter timelines", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/masterLayoutOptions.md")

}
System(140523039151328, $label="Twitter", $descr="", $link="https://github.com/plantuml-stdlib/C4-PlantUML")



Rel(140523039151184, 140523039151232, "Uses", "HTTPS", "", $link="https://plantuml.com/link")
Rel(140523039151232, 140523039151328, "Gets tweets from", "HTTPS", "", $link="https://plantuml.com/link")
SHOW_LEGEND()
@enduml
