@startuml

!include C4_Dynamic.puml


AddElementTag("v1.0", $borderColor="#d73027")
AddElementTag("v1.1", $fontColor="#d73027")
AddElementTag("backup", $fontColor="orange")
Person(140523039151856, $label="Customer", $descr="People that need products")
Person(140523039151952, $label="Administrator", $descr="People that administrates the products via the new v1.1 components", $tags="v1.1")

Container(140523039152000, $label="SPA", $techn="angular", $descr="The main interface that the customer interacts with via v1.0", $tags="v1.0")
Container(140523039152048, $label="Admin SPA", $techn="angular", $descr="The administrator interface that the customer interacts with via new v1.1", $tags="v1.1")
Container(140523039152096, $label="API", $techn="java", $descr="Handles all business logic (incl. new v1.1 extensions)", $tags="v1.0+v1.1")
ContainerDb(140523039152144, $label="Database", $techn="Microsoft SQL", $descr="Holds product, order and invoice information")
Container(140523039152192, $label="Archive", $techn="Audit logging", $descr="Stores 5 years", $tags="backup")


Rel(140523039151856, 140523039152000, "Uses", "https", "")
Rel(140523039152000, 140523039152096, "Uses", "https", "")
Rel_R(140523039152096, 140523039152144, "Reads/Writes", "", "")
Rel(140523039151952, 140523039152048, "Uses", "https", "")
Rel(140523039152048, 140523039152096, "Uses", "https", "")
Rel_L(140523039152096, 140523039152192, "Writes", "messages", "", $tags="backup")
SHOW_LEGEND()
@enduml
