@startuml

hide empty description

state 57 <<start>>
state "State1" as 58
58 : this is a string
58 : this is another string
state "State2" as 59
state 60 <<end>>

57 --> 58
58 --> 59
58 --> 60
59 --> 60

@enduml
