@startuml

hide empty description

state 15 <<start>>
state "State1" as 16
16 : this is a string
16 : this is another string
state "State2" as 17
state 18 <<end>>

15 --> 16
16 --> 17
16 --> 18
17 --> 18

@enduml
