@startuml

hide empty description

state 36 <<start>>
state "State1" as 37
37 : this is a string
37 : this is another string
state "State2" as 38
state 39 <<end>>

36 --> 37
37 --> 38
37 --> 39
38 --> 39

@enduml
