@startuml

state 38 <<start>>
state "NotShooting" as 41 {
    state 39 <<start>>
    state "Idle" as 40
}
state "Configuring" as 47 {
    state 42 <<start>>
    state "NewValueSelection" as 43
    state "NewValuePreview" as 46 {
        state "State1" as 44
        state "State2" as 45
    }
}

38 --> 41
39 --> 40
40 --> 47 : EvConfig
47 --> 40 : EvConfig
42 --> 43
43 --> 46 : EvNewValue
46 --> 43 : EvNewValueRejected
46 --> 43 : EvNewValueSaved
44 --> 45

@enduml
