@startuml

state 10 <<start>>
state "NotShooting" as 13 {
    state 11 <<start>>
    state "Idle" as 12
}
state "Configuring" as 19 {
    state 14 <<start>>
    state "NewValueSelection" as 15
    state "NewValuePreview" as 18 {
        state "State1" as 16
        state "State2" as 17
    }
}

10 --> 13
11 --> 12
12 --> 19 : EvConfig
19 --> 12 : EvConfig
14 --> 15
15 --> 18 : EvNewValue
18 --> 15 : EvNewValueRejected
18 --> 15 : EvNewValueSaved
16 --> 17

@enduml
