@startuml

state 30 <<start>>
state "State1" as 31
state "State2" as 32
state "State3" as 36 {
    state 33 <<start>>
    state "Accumulate Enough Data" as 34
    34 : Just a test
    state "ProcessData" as 35
}
state 37 <<end>>

30 --> 31
31 --> 32 : Succeeded
32 --> 36 : Succeeded
31 --> 37 : Aborted
32 --> 37 : Aborted
36 --> 37 : Succeeded / Save Result
36 --> 37 : Aborted
33 --> 34
34 --> 34 : New Data
34 --> 35 : Enough Data

@enduml
