@startuml

state 25 <<start>>
state "State1" as 26
state "State2" as 27
state "State3" as 31 {
    state 28 <<start>>
    state "Accumulate Enough Data" as 29
    29 : Just a test
    state "ProcessData" as 30
}
state 32 <<end>>

25 --> 26
26 --> 27 : Succeeded
27 --> 31 : Succeeded
26 --> 32 : Aborted
27 --> 32 : Aborted
31 --> 32 : Succeeded / Save Result
31 --> 32 : Aborted
28 --> 29
29 --> 29 : New Data
29 --> 30 : Enough Data

@enduml
