@startuml

state 39 <<start>>
state "State1" as 40
state "State2" as 41
state "State3" as 45 {
    state 42 <<start>>
    state "Accumulate Enough Data" as 43
    43 : Just a test
    state "ProcessData" as 44
}
state 46 <<end>>

39 --> 40
40 --> 41 : Succeeded
41 --> 45 : Succeeded
40 --> 46 : Aborted
41 --> 46 : Aborted
45 --> 46 : Succeeded / Save Result
45 --> 46 : Aborted
42 --> 43
43 --> 43 : New Data
43 --> 44 : Enough Data

@enduml
