@startuml

state 22 <<start>>
state "State1" as 23
state "State2" as 24
state "State3" as 28 {
    state 25 <<start>>
    state "Accumulate Enough Data" as 26
    26 : Just a test
    state "ProcessData" as 27
}
state 29 <<end>>

22 --> 23
23 --> 24 : Succeeded
24 --> 28 : Succeeded
24 --> 28[H] : Resume
24 --> 28[H*] : DeepResume
28 --> 24 : Pause
28 --> 28 : Failed
23 --> 29 : Aborted
24 --> 29 : Aborted
28 --> 29 : Succeeded / Save Result
28 --> 29 : Aborted
25 --> 26
26 --> 26 : New Data
26 --> 27 : Enough Data

@enduml
