@startuml

state 13 <<start>>
state "State1" as 14
state "State2" as 15
state "State3" as 19 {
    state 16 <<start>>
    state "Accumulate Enough Data" as 17
    17 : Just a test
    state "ProcessData" as 18
}
state 20 <<end>>

13 --> 14
14 --> 15 : Succeeded
15 --> 19 : Succeeded
15 --> 19[H] : Resume
15 --> 19[H*] : DeepResume
19 --> 15 : Pause
19 --> 19 : Failed
14 --> 20 : Aborted
15 --> 20 : Aborted
19 --> 20 : Succeeded / Save Result
19 --> 20 : Aborted
16 --> 17
17 --> 17 : New Data
17 --> 18 : Enough Data

@enduml
