@startuml

state 6 <<start>>
state 7 <<fork>>
state "State2" as 8
state "State3" as 9
state 10 <<join>>
state "State4" as 11
state 12 <<end>>

6 --> 7
7 --> 8
7 --> 9
8 --> 10
9 --> 10
10 --> 11
11 --> 12

@enduml
