stateDiagram-v2
state First {
fir
[*] --> fir 
fir --> [*] 
}
state Second {
sec
[*] --> sec 
sec --> [*] 
}
state Third {
thi
[*] --> thi 
thi --> [*] 
}
[*] --> First 
First --> Second 
First --> Third 