stateDiagram-v2
state ForkState <<fork>>
state JoinState <<join>>
State2
State3
State4
[*] --> ForkState 
ForkState --> State2 
ForkState --> State3 
State2 --> JoinState 
State3 --> JoinState 
JoinState --> State4 
State4 --> [*] 